// <auto-generated />
using Flight.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Flight.Migrations
{
    [DbContext(typeof(FlightContext))]
    [Migration("20180222114030_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("Flight.Models.AirRoutes", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("From");

                    b.Property<int>("Price");

                    b.Property<int>("Stops");

                    b.Property<string>("To");

                    b.Property<DateTime>("arrival");

                    b.Property<DateTime>("departing");

                    b.Property<string>("seatsAvailable");

                    b.HasKey("ID");

                    b.ToTable("AirRoutes");
                });
#pragma warning restore 612, 618
        }
    }
}
